spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  redis:
    host: ${vcap.services.catalog-redis.credentials.hostname:10.0.0.12}
    port: ${vcap.services.catalog-redis.credentials.port:6379}
---
spring:
  profiles: development
  redis:
    host: 10.0.0.12
    port: 6379
  datasource:
    url: jdbc:mysql://10.0.0.12:3306/dev?useSSL=false
    username: root
    password: Bn@Oracle.admin.19
    initialize: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
---
spring:
  profiles: docker
  redis:
    host: 10.0.0.12
    port: 6379
  datasource:
    url: jdbc:mysql://10.0.0.12:3306/dev?useSSL=false
    username: root
    password: Bn@Oracle.admin.19
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: 10.0.0.12
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false
