spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: ${vcap.services.edge-service.credentials.uri:http://edge.micro-demo.com}
    auth-service:
      path: /user/**
      url: ${vcap.services.user-service.credentials.uri:http://user.micro-demo.com}/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://user.micro-demo.com}/uaa/user
    client:
      accessTokenUri: ${vcap.services.user-service.credentials.uri:http://user.micro-demo.com}/uaa/oauth/token
      userAuthorizationUri: ${vcap.services.user-service.credentials.uri:http://user.micro-demo.com}/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://edge.micro-demo.com
    auth-service:
      path: /user/**
      url: http://user.micro-demo.com/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://user.micro-demo.com/uaa/user
    client:
      accessTokenUri: http://user.micro-demo.com/uaa/oauth/token
      userAuthorizationUri: http://user.micro-demo.com/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://edge.micro-demo.com
    auth-service:
      path: /user/**
      url: http://user.micro-demo.com/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://user.micro-demo.com/uaa/user
    client:
      accessTokenUri: http://user.micro-demo.com/uaa/oauth/token
      userAuthorizationUri: http://user.micro-demo.com/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
