spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  datasource:
    platform: mysql
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://user.micro-demo.com}/uaa/user
    client:
      client-id: acme
  enable-csrf: false
---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://10.0.0.12:3306/dev
    username: root
    password: Bn@Oracle.admin.19
security:
  oauth2:
    resource:
      userInfoUri: http://user.micro-demo.com/uaa/user
    client:
      client-id: acme
      access-token-uri: http://online-store.micro-demo.com
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
---
spring:
  profiles: docker
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://10.0.0.12:3306/dev
    username: root
    password: Bn@Oracle.admin.19
security:
  oauth2:
    resource:
      userInfoUri: http://user.micro-demo.com1/uaa/user
    client:
      client-id: acme
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
---
spring:
  application:
    name: account-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
security:
  oauth2:
    resource:
      userInfoUri: http://user.micro-demo.com/uaa/user
    client:
      client-id: acme
      access-token-uri: http://online-store.micro-demo.com
